vich_uploader:
    db_driver: orm
    twig: true
    metadata:
        type: attribute
    mappings:
        project_images:
            uri_prefix: /uploads/projects
            upload_destination: '%kernel.project_dir%/public/uploads/projects'
            inject_on_load: true
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer:
                service: vich_uploader.namer_directory_property
                options: { property: 'projectId', transliterate: true }

