#production:
#  stage: production
#  hostname:
#  user:
#  identityFile: ~/.ssh/id_rsa
#  forwardAgent: true
#  branch: main
#  deploy_path:
#  env:
#    APP_ENV: 'prod'

development:
  stage: development
  hostname: oleu.moyak.de
  user: moyak.de
  identityFile: ~/.ssh/id_rsa
  forwardAgent: true
  branch: main
  deploy_path: ~/httpdocs/oleu.moyak.de
  env:
    APP_ENV: prod
    APP_DEBUG: 0
    SYMFONY_ENV: